import type { ReferenceSet } from "./types";

/**
 * Writes the reference set as SQL: the data migration (a full upsert, so a later refresh of the
 * source documents becomes a new migration of the same form) and the pgTAP test that proves the
 * loaded tables hold exactly these rows. Both are generated from `reference.json` and checked by
 * `reference.test.ts`; neither is edited by hand.
 */

interface TableSpec {
  table: string;
  key: readonly string[];
  columns: readonly string[];
  rows: (set: ReferenceSet) => readonly object[];
}

function field(row: object, column: string): unknown {
  return (row as Record<string, unknown>)[column];
}

/** In dependency order: parents before children. */
export const TABLES: readonly TableSpec[] = [
  {
    table: "ref_survey_sections",
    key: ["code"],
    columns: ["code", "heading", "position"],
    rows: (s) => s.survey_sections,
  },
  {
    table: "ref_survey_items",
    key: ["code"],
    columns: [
      "code",
      "block",
      "sub_construct",
      "wording",
      "is_reverse",
      "in_baseline",
      "in_pulse",
      "pulse_rotates",
      "in_half_yearly",
      "in_annual",
      "section",
      "position",
    ],
    rows: (s) => s.survey_items,
  },
  {
    table: "ref_pulse_rotation",
    key: ["rotation", "item_code"],
    columns: ["rotation", "item_code"],
    rows: (s) => s.pulse_rotation,
  },
  {
    table: "ref_modules",
    key: ["code"],
    columns: [
      "code",
      "audience",
      "sub_dimension",
      "repeats_over",
      "disclosure",
      "source",
      "position",
    ],
    rows: (s) => s.modules,
  },
  {
    table: "ref_module_items",
    key: ["code"],
    columns: [
      "code",
      "module_code",
      "position",
      "wording",
      "response_kind",
      "anchors",
      "is_reverse",
      "online",
      "portal_code",
    ],
    rows: (s) => s.module_items,
  },
  {
    table: "ref_admin_checklists",
    key: ["code"],
    columns: ["code", "repeats_over", "minimum_facts", "source", "position"],
    rows: (s) => s.checklists,
  },
  {
    table: "ref_admin_checklist_facts",
    key: ["code"],
    columns: ["code", "checklist_code", "position", "wording", "response_kind", "source_response"],
    rows: (s) => s.checklist_facts,
  },
  {
    table: "ref_admin_checklist_values",
    key: ["fact_code", "option"],
    columns: ["fact_code", "option", "label", "value", "position"],
    rows: (s) => s.checklist_values,
  },
  {
    table: "ref_admin_checklist_bands",
    key: ["fact_code", "position"],
    columns: [
      "fact_code",
      "position",
      "score",
      "lower",
      "lower_inclusive",
      "upper",
      "upper_inclusive",
    ],
    rows: (s) => s.checklist_bands,
  },
  {
    table: "ref_event_triggers",
    key: ["code"],
    columns: ["code", "source_trigger", "affects", "detection", "deploys", "source", "position"],
    rows: (s) => s.event_triggers,
  },
];

function literal(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
  if (Array.isArray(value) && value.every((v) => typeof v === "string")) {
    return value.length === 0 ? "'{}'::text[]" : `array[${value.map(literal).join(", ")}]`;
  }
  return `${literal(JSON.stringify(value))}::jsonb`;
}

const HEADER = `-- Generated by apps/portal/lib/reference from the source documents in docs/source-ip
-- (\`pnpm --filter @performancevp/portal reference\`). Do not edit: change the source or the
-- interpretation, regenerate, and let reference.test.ts confirm it. When a source document changes
-- after this migration has been applied, generate a new migration of the same form rather than
-- editing this one.`;

export function migrationSql(set: ReferenceSet, title: string): string {
  const out: string[] = [`-- ${title}`, "--", HEADER, ""];
  for (const spec of TABLES) {
    const rows = spec.rows(set);
    const updates = spec.columns.filter((c) => !spec.key.includes(c));
    out.push(`-- ${spec.table}: ${rows.length} rows.`);
    out.push(`insert into public.${spec.table} (${spec.columns.join(", ")}) values`);
    out.push(
      rows
        .map((row) => `  (${spec.columns.map((c) => literal(field(row, c))).join(", ")})`)
        .join(",\n"),
    );
    out.push(
      updates.length === 0
        ? `on conflict (${spec.key.join(", ")}) do nothing;`
        : `on conflict (${spec.key.join(", ")}) do update set\n  ${updates.map((c) => `${c} = excluded.${c}`).join(",\n  ")};`,
    );
    out.push("");
  }
  // Rows no longer in the source go, children first.
  for (const spec of [...TABLES].reverse()) {
    const rows = spec.rows(set);
    const keyTuple = spec.key.length === 1 ? spec.key[0] : `(${spec.key.join(", ")})`;
    const values = rows
      .map((row) =>
        spec.key.length === 1
          ? literal(field(row, spec.key[0]!))
          : `(${spec.key.map((k) => literal(field(row, k))).join(", ")})`,
      )
      .join(", ");
    out.push(`delete from public.${spec.table} where ${keyTuple} not in (${values});`);
  }
  return `${out.join("\n")}\n`;
}

export function pgtapSql(set: ReferenceSet): string {
  const out: string[] = [
    "-- The reference tables hold exactly the rows generated from the source documents (Milestone 5",
    "-- plan, Section 1.2): the last link of the chain source, JSON, migration, database.",
    "--",
    HEADER,
    "begin;",
    "",
    `select plan(${TABLES.length});`,
    "",
  ];
  for (const spec of TABLES) {
    const expected = spec.rows(set).map((row) => {
      const ordered: Record<string, unknown> = {};
      for (const c of spec.columns) ordered[c] = field(row, c) ?? null;
      return ordered;
    });
    out.push(
      `select set_eq(\n  $$ select to_jsonb(t) from public.${spec.table} t $$,\n  $$ select jsonb_array_elements($json$${JSON.stringify(expected)}$json$::jsonb) $$,\n  '${spec.table} holds exactly the generated rows'\n);`,
    );
    out.push("");
  }
  out.push("select * from finish();", "", "rollback;");
  return `${out.join("\n")}\n`;
}
