-- Milestone 5, step 1: the reference rows, generated from the source documents.
--
-- Generated by apps/portal/lib/reference from the source documents in docs/source-ip
-- (`pnpm --filter @performancevp/portal reference`). Do not edit: change the source or the
-- interpretation, regenerate, and let reference.test.ts confirm it. When a source document changes
-- after this migration has been applied, generate a new migration of the same form rather than
-- editing this one.

-- ref_survey_sections: 3 rows.
insert into public.ref_survey_sections (code, heading, position) values
  ('A', 'About your team and work', 1),
  ('B', 'About your role and environment', 2),
  ('C', 'About your motivation and experience', 3)
on conflict (code) do update set
  heading = excluded.heading,
  position = excluded.position;

-- ref_survey_items: 71 rows.
insert into public.ref_survey_items (code, block, sub_construct, wording, is_reverse, in_baseline, in_pulse, pulse_rotates, in_half_yearly, in_annual, section, position) values
  ('CII-01', 'C4', 'clarity', 'Our team has a clear understanding of who the subject matter experts are for different aspects of our work.', false, true, false, false, true, true, 'A', 1),
  ('CII-02', 'C4', 'clarity', 'When I need specific expertise, I know exactly who on the team to go to.', false, true, false, false, true, true, 'A', 2),
  ('CII-06', 'C4', 'trust', 'I trust the work my team members produce without needing to second-guess it.', false, true, false, false, true, true, 'A', 3),
  ('CII-07', 'C4', 'trust', 'When a colleague gives me information or advice, I act on it with confidence.', false, true, false, false, true, true, 'A', 4),
  ('CII-11', 'C4', 'flow', 'Information moves across our team without bottlenecks.', false, true, false, false, true, true, 'A', 5),
  ('CII-12', 'C4', 'flow', 'Our team combines individual knowledge into collective output smoothly.', false, true, false, false, true, true, 'A', 6),
  ('TSI2-01', 'S2', null, 'Our team has enough uninterrupted time to focus on meaningful work.', false, true, true, false, true, true, 'A', 7),
  ('TSI2-02', 'S2', null, 'Handoffs between our team and other groups work smoothly.', false, true, true, false, true, true, 'A', 8),
  ('TSI3-01', 'S3', 'task', 'On our team, we challenge each other''s ideas openly when we disagree about how to do the work.', false, true, false, false, true, true, 'A', 9),
  ('TSI3-02', 'S3', 'task', 'When we have different opinions about how to approach a problem, we debate them productively.', false, true, false, false, true, true, 'A', 10),
  ('CII-03', 'C4', 'clarity', 'Team members openly acknowledge their areas of strength and the areas where others know more.', false, true, false, false, true, true, 'A', 11),
  ('CII-04', 'C4', 'clarity', 'We make good use of the different expertise across our team.', false, true, false, false, true, true, 'A', 12),
  ('CII-08', 'C4', 'trust', 'We openly trust each other''s professional judgement on complex issues.', false, true, false, false, true, true, 'A', 13),
  ('CII-09', 'C4', 'trust', 'Our team treats each other''s expertise as reliable and authoritative.', false, true, false, false, true, true, 'A', 14),
  ('CII-13', 'C4', 'flow', 'We adapt quickly to new challenges because we know how to draw on each other''s strengths.', false, true, true, true, true, true, 'A', 15),
  ('CII-14', 'C4', 'flow', 'Coordinating expertise across our team feels effortless rather than forced.', false, true, false, false, true, true, 'A', 16),
  ('TSI2-03', 'S2', null, 'I spend too much of my week in meetings that don''t really need me.', true, true, true, false, true, true, 'A', 17),
  ('TSI3-03', 'S3', 'task', 'Our team is comfortable having robust discussions about work decisions.', false, true, false, false, false, true, 'A', 18),
  ('TSI3-04', 'S3', 'relationship', 'There is real interpersonal friction or animosity on our team.', true, true, false, false, true, true, 'A', 19),
  ('TSI3-05', 'S3', 'relationship', 'Personality clashes affect how well our team gets work done.', true, true, false, false, false, true, 'A', 20),
  ('CII-05', 'C4', 'clarity', 'When a new problem arises, it is often unclear who has the relevant knowledge to address it.', true, true, false, false, true, true, 'A', 21),
  ('CII-10', 'C4', 'trust', 'I often feel I need to verify my colleagues'' work before relying on it.', true, true, false, false, true, true, 'A', 22),
  ('CII-15', 'C4', 'flow', 'It often takes too long to bring the right people and information together to solve a problem.', true, true, false, false, true, true, 'A', 23),
  ('OI1-01', 'O1', 'role_clarity', 'I am clear on what is expected of me in my role.', false, true, false, false, true, true, 'B', 24),
  ('OI1-02', 'O1', 'role_clarity', 'I know how my performance is evaluated and what success looks like in my role.', false, true, false, false, true, true, 'B', 25),
  ('OI1-04', 'O1', 'decision_rights', 'I have the authority I need to make decisions about my own work.', false, true, false, false, true, true, 'B', 26),
  ('OI1-05', 'O1', 'decision_rights', 'It''s clear in this team who has authority to make which decisions.', false, true, false, false, true, true, 'B', 27),
  ('OI1-07', 'O1', 'cascade', 'I understand how my work connects to the organisation''s strategic priorities.', false, true, false, false, true, true, 'B', 28),
  ('OI1-08', 'O1', 'cascade', 'The goals my team is working towards are clearly linked to the broader organisation''s goals.', false, true, false, false, false, true, 'B', 29),
  ('OI1-03', 'O1', 'role_clarity', 'I often receive conflicting instructions about what I should be doing.', true, true, false, false, false, true, 'B', 30),
  ('OI1-06', 'O1', 'decision_rights', 'Decisions that should be made quickly often get held up needing extra approvals.', true, true, false, false, false, true, 'B', 31),
  ('OI2-01', 'O2', null, 'I have the tools and systems I need to do my work effectively.', false, true, false, false, true, true, 'B', 32),
  ('OI2-02', 'O2', null, 'I can get the information and data I need to do my work without unreasonable delay.', false, true, false, false, true, true, 'B', 33),
  ('OI2-03', 'O2', null, 'The tools we use work well together rather than against each other.', false, true, false, false, true, true, 'B', 34),
  ('OI2-04', 'O2', null, 'I often have to use workarounds because our systems don''t do what I need them to.', true, true, false, false, true, true, 'B', 35),
  ('OI3-01', 'O3', null, 'The processes we use to get work done are clear and easy to follow.', false, true, false, false, true, true, 'B', 36),
  ('OI3-02', 'O3', null, 'Work moves through our team without getting stuck in unnecessary steps or approvals.', false, true, false, false, true, true, 'B', 37),
  ('OI3-03', 'O3', null, 'I spend an appropriate amount of my time on the work that actually matters, not on admin or rework.', false, true, false, false, true, true, 'B', 38),
  ('OI3-04', 'O3', null, 'When something goes wrong, we have a clear way to fix it without making the whole process slow.', false, true, false, false, true, true, 'B', 39),
  ('OI3-05', 'O3', null, 'A lot of the work I do feels like duplicate effort or rework.', true, true, false, false, true, true, 'B', 40),
  ('OI4-01', 'O4', null, 'I have enough time to do my work to the standard expected.', false, true, false, false, true, true, 'B', 41),
  ('OI4-02', 'O4', null, 'Our team has the resources (people, budget, capacity) it needs to deliver what''s being asked.', false, true, false, false, true, true, 'B', 42),
  ('OI4-03', 'O4', null, 'I regularly have to work outside normal hours just to keep up with my workload.', true, true, false, false, true, true, 'B', 43),
  ('OI5-01', 'O5', null, 'My manager helps me remove obstacles that are getting in the way of my work.', false, true, true, false, true, true, 'B', 44),
  ('OI5-02', 'O5', null, 'My manager backs my decisions and gives me appropriate latitude to act.', false, true, true, false, true, true, 'B', 45),
  ('OI5-03', 'O5', null, 'My manager actively makes our team''s work easier rather than harder.', false, true, true, false, true, true, 'B', 46),
  ('MI1-01', 'M1', 'engagement', 'I look forward to coming to work most days.', false, true, true, true, true, true, 'C', 47),
  ('MI1-02', 'M1', 'engagement', 'I am willing to put in extra effort when my team needs it.', false, true, true, true, true, true, 'C', 48),
  ('MI1-03', 'M1', 'engagement', 'When I''m working, time tends to fly by.', false, true, false, false, true, true, 'C', 49),
  ('MI1-05', 'M1', 'team_confidence', 'I am confident our team can deliver on the goals we''ve been set.', false, true, true, true, true, true, 'C', 50),
  ('MI1-06', 'M1', 'team_confidence', 'When our team faces tough problems, we find a way through them.', false, true, false, false, true, true, 'C', 51),
  ('MI1-07', 'M1', 'pride', 'I''d recommend this organisation as a good place to work.', false, true, true, true, true, true, 'C', 52),
  ('MI1-08', 'M1', 'pride', 'I feel proud to be part of this team and organisation.', false, true, false, false, true, true, 'C', 53),
  ('MI1-04', 'M1', 'engagement', 'I often feel drained or disengaged at work.', true, true, true, true, true, true, 'C', 54),
  ('MI2-01', 'M2', null, 'On our team, people can raise concerns or disagreements without fear of being penalised.', false, true, true, true, true, true, 'C', 55),
  ('MI2-02', 'M2', null, 'If I make a mistake at work, I feel safe disclosing it so we can fix it and learn.', false, true, true, true, true, true, 'C', 56),
  ('MI2-03', 'M2', null, 'Our team discusses difficult issues openly rather than avoiding them.', false, true, true, true, true, true, 'C', 57),
  ('MI2-04', 'M2', null, 'I can voice an opinion that goes against the group view without it damaging my standing.', false, true, false, false, true, true, 'C', 58),
  ('MI2-05', 'M2', null, 'People on this team often get punished or dismissed for raising problems.', true, true, false, false, true, true, 'C', 59),
  ('MI3-01', 'M3', null, 'I do my work because I find it genuinely interesting.', false, true, false, false, false, true, 'C', 60),
  ('MI3-02', 'M3', null, 'The work I do aligns with what I personally value as important.', false, true, false, false, false, true, 'C', 61),
  ('MI3-03', 'M3', null, 'I have meaningful choice in how I do my work.', false, true, false, false, false, true, 'C', 62),
  ('MI3-05', 'M3', null, 'When I do my work well, I feel a sense of personal accomplishment from it.', false, true, false, false, false, true, 'C', 63),
  ('MI3-04', 'M3', null, 'I do my work mainly because I have to, not because I want to.', true, true, false, false, false, true, 'C', 64),
  ('MI4-01', 'M4', null, 'My work has personal meaning for me.', false, true, false, false, false, true, 'C', 65),
  ('MI4-02', 'M4', null, 'The purpose of this organisation is something I can stand behind.', false, true, false, false, false, true, 'C', 66),
  ('MI4-03', 'M4', null, 'What I do at work matters in a broader sense, beyond the immediate task.', false, true, false, false, false, true, 'C', 67),
  ('MI4-04', 'M4', null, 'I struggle to see why what we do really matters.', true, true, false, false, false, true, 'C', 68),
  ('TW-01', 'TW', null, 'I am paid fairly for the work I do compared to others in similar roles.', false, true, true, true, true, true, 'C', 69),
  ('TW-02', 'TW', null, 'People in this team are treated fairly and respectfully regardless of their background.', false, true, true, true, true, true, 'C', 70),
  ('TW-03', 'TW', null, 'I have the basic working conditions (workspace, tools, safety, time) I need to do my job.', false, true, true, true, true, true, 'C', 71)
on conflict (code) do update set
  block = excluded.block,
  sub_construct = excluded.sub_construct,
  wording = excluded.wording,
  is_reverse = excluded.is_reverse,
  in_baseline = excluded.in_baseline,
  in_pulse = excluded.in_pulse,
  pulse_rotates = excluded.pulse_rotates,
  in_half_yearly = excluded.in_half_yearly,
  in_annual = excluded.in_annual,
  section = excluded.section,
  position = excluded.position;

-- ref_pulse_rotation: 68 rows.
insert into public.ref_pulse_rotation (rotation, item_code) values
  (1, 'TSI2-01'),
  (1, 'TSI2-02'),
  (1, 'CII-13'),
  (1, 'TSI2-03'),
  (1, 'OI5-01'),
  (1, 'OI5-02'),
  (1, 'OI5-03'),
  (1, 'MI1-01'),
  (1, 'MI1-02'),
  (1, 'MI1-05'),
  (1, 'MI1-07'),
  (1, 'MI1-04'),
  (1, 'MI2-01'),
  (1, 'MI2-02'),
  (1, 'MI2-03'),
  (1, 'TW-01'),
  (1, 'TW-02'),
  (2, 'TSI2-01'),
  (2, 'TSI2-02'),
  (2, 'CII-13'),
  (2, 'TSI2-03'),
  (2, 'OI5-01'),
  (2, 'OI5-02'),
  (2, 'OI5-03'),
  (2, 'MI1-01'),
  (2, 'MI1-03'),
  (2, 'MI1-05'),
  (2, 'MI1-08'),
  (2, 'MI1-04'),
  (2, 'MI2-01'),
  (2, 'MI2-02'),
  (2, 'MI2-04'),
  (2, 'TW-02'),
  (2, 'TW-03'),
  (3, 'TSI2-01'),
  (3, 'TSI2-02'),
  (3, 'CII-13'),
  (3, 'TSI2-03'),
  (3, 'OI5-01'),
  (3, 'OI5-02'),
  (3, 'OI5-03'),
  (3, 'MI1-02'),
  (3, 'MI1-03'),
  (3, 'MI1-05'),
  (3, 'MI1-06'),
  (3, 'MI1-07'),
  (3, 'MI2-02'),
  (3, 'MI2-03'),
  (3, 'MI2-05'),
  (3, 'TW-01'),
  (3, 'TW-03'),
  (4, 'TSI2-01'),
  (4, 'TSI2-02'),
  (4, 'CII-13'),
  (4, 'TSI2-03'),
  (4, 'OI5-01'),
  (4, 'OI5-02'),
  (4, 'OI5-03'),
  (4, 'MI1-01'),
  (4, 'MI1-02'),
  (4, 'MI1-06'),
  (4, 'MI1-08'),
  (4, 'MI1-04'),
  (4, 'MI2-01'),
  (4, 'MI2-03'),
  (4, 'MI2-04'),
  (4, 'TW-01'),
  (4, 'TW-02')
on conflict (rotation, item_code) do nothing;

-- ref_modules: 8 rows.
insert into public.ref_modules (code, audience, sub_dimension, repeats_over, disclosure, source, position) values
  ('M-O1-CASCADE', 'members_part_b', 'O1', 'none', 'none', 'Tier 3 Module Library 2.1', 1),
  ('M-O2-IA', 'members_part_b', 'O2', 'none', 'none', 'Tier 3 Module Library 2.2', 2),
  ('M-O3-PF', 'members_part_b', 'O3', 'process', 'none', 'Tier 3 Module Library 2.3', 3),
  ('M-O1-LT', 'leadership_team', 'O1', 'decision_type', 'leadership_team', 'Tier 3 Module Library 3.1 and 8.3', 4),
  ('M-C1-MGR', 'managers', 'C1', 'report_skill', 'none', 'Tier 3 Module Library 4.1', 5),
  ('M-C2-MGR', 'managers', 'C2', 'report_domain', 'none', 'Online Measurement Specification 4.1', 6),
  ('M-C3-MGR', 'managers', 'C3', 'report', 'none', 'Tier 3 Module Library 4.2', 7),
  ('M-C5-TL', 'team_leaders', 'C5', 'none', 'small_group', 'Tier 3 Module Library 5.1 and 8.4', 8)
on conflict (code) do update set
  audience = excluded.audience,
  sub_dimension = excluded.sub_dimension,
  repeats_over = excluded.repeats_over,
  disclosure = excluded.disclosure,
  source = excluded.source,
  position = excluded.position;

-- ref_module_items: 41 rows.
insert into public.ref_module_items (code, module_code, position, wording, response_kind, anchors, is_reverse, online, portal_code) values
  ('O1C-01', 'M-O1-CASCADE', 1, 'I can clearly describe how my work contributes to our team''s goals.', 'agree5', null, false, true, false),
  ('O1C-02', 'M-O1-CASCADE', 2, 'I can clearly describe how my team''s goals connect to the organisation''s broader priorities.', 'agree5', null, false, true, false),
  ('O1C-03', 'M-O1-CASCADE', 3, 'I know what our organisation is trying to achieve and why.', 'agree5', null, false, true, false),
  ('O1C-04', 'M-O1-CASCADE', 4, 'When priorities change at the organisation level, the implications for my work are explained clearly.', 'agree5', null, false, true, false),
  ('O1C-05', 'M-O1-CASCADE', 5, 'Sometimes I find myself doing work that doesn''t seem to connect to what the organisation is trying to achieve.', 'agree5', null, true, true, false),
  ('O2I-01', 'M-O2-IA', 1, 'When I need information to do my work, I can find it without significant delay.', 'agree5', null, false, true, false),
  ('O2I-02', 'M-O2-IA', 2, 'The information available to me is accurate and current.', 'agree5', null, false, true, false),
  ('O2I-03', 'M-O2-IA', 3, 'I often need to ask colleagues for information that should be available in our systems.', 'agree5', null, true, true, false),
  ('O2I-04', 'M-O2-IA', 4, 'I spend significant time each week working around limitations in our tools or systems.', 'agree5', null, true, true, false),
  ('O2I-05', 'M-O2-IA', 5, 'The systems I use to do my work integrate well with each other.', 'agree5', null, false, true, false),
  ('O2I-06', 'M-O2-IA', 6, 'I sometimes have to re-enter or copy information between systems that should connect automatically.', 'agree5', null, true, true, false),
  ('O2I-07', 'M-O2-IA', 7, 'What is the single most significant tool or information access issue in your work? (Optional, open-text)', 'open_text', null, false, false, false),
  ('O3P-01', 'M-O3-PF', 1, 'This process is clear and easy to follow.', 'agree5', null, false, true, false),
  ('O3P-02', 'M-O3-PF', 2, 'Work moves through this process without unnecessary delays or approvals.', 'agree5', null, false, true, false),
  ('O3P-03', 'M-O3-PF', 3, 'Information and inputs are typically ready when this process needs them.', 'agree5', null, false, true, false),
  ('O3P-04', 'M-O3-PF', 4, 'When something needs to be reworked or corrected in this process, the rework usually slows it down significantly.', 'agree5', null, true, true, false),
  ('O3P-05', 'M-O3-PF', 5, 'Handoffs in this process (between people, teams or systems) work smoothly.', 'agree5', null, false, true, false),
  ('O3P-06', 'M-O3-PF', 6, 'I spend appropriate time on the value-adding parts of this process, not on admin or workarounds.', 'agree5', null, false, true, false),
  ('O3P-07', 'M-O3-PF', 7, 'Where in this process is the biggest bottleneck or source of friction? (Optional, open-text)', 'open_text', null, false, false, false),
  ('O1L-01', 'M-O1-LT', 1, 'Who Recommends this decision?', 'rapid_multi', null, false, true, true),
  ('O1L-02', 'M-O1-LT', 2, 'Who Agrees must be consulted before this decision?', 'rapid_multi', null, false, true, true),
  ('O1L-03', 'M-O1-LT', 3, 'Who Performs (implements) this decision?', 'rapid_multi', null, false, true, true),
  ('O1L-04', 'M-O1-LT', 4, 'Who provides Input on this decision?', 'rapid_multi', null, false, true, true),
  ('O1L-05', 'M-O1-LT', 5, 'Who Decides (has decision authority) on this decision?', 'rapid_single', null, false, true, true),
  ('O1L-06', 'M-O1-LT', 6, 'How clear are the decision rights for this type of decision?', 'anchored5', '[{"value":1,"label":"Very unclear","description":null},{"value":5,"label":"Very clear","description":null}]'::jsonb, false, true, true),
  ('C1M-01', 'M-C1-MGR', 1, '[Skill name]: rate this person''s current demonstrated proficiency', 'anchored5', '[{"value":1,"label":"Novice","description":null},{"value":2,"label":"Developing","description":null},{"value":3,"label":"Proficient","description":null},{"value":4,"label":"Advanced","description":null},{"value":5,"label":"Expert","description":null}]'::jsonb, false, true, true),
  ('C2M-01', 'M-C2-MGR', 1, '[Domain name]: rate this person''s current working knowledge', 'anchored5', '[{"value":1,"label":"Little working knowledge","description":null},{"value":2,"label":"Basic; needs frequent reference or help","description":null},{"value":3,"label":"Sound working knowledge for the role","description":null},{"value":4,"label":"Deep knowledge; handles non-routine cases","description":null},{"value":5,"label":"An authority others consult","description":null}]'::jsonb, false, true, true),
  ('C3M-01', 'M-C3-MGR', 1, 'Performance band', 'band5', '[{"value":1,"label":"Underperforming","description":"Consistent gaps in delivery; performance management intervention warranted"},{"value":2,"label":"Developing / partial meet","description":"Meets some expectations; gaps in delivery quality or scope"},{"value":3,"label":"Meeting expectations","description":"Delivers reliably at the role''s expected standard"},{"value":4,"label":"Exceeding expectations","description":"Consistently delivers above the role''s expected standard"},{"value":5,"label":"Exceptional contributor","description":"Consistently exceeds expectations in scope and quality; recognised as a top performer"}]'::jsonb, false, true, true),
  ('C3M-02', 'M-C3-MGR', 2, 'Evidence basis', 'evidence_note', null, false, true, true),
  ('C5L-01', 'M-C5-TL', 1, 'How long does it typically take for a new team member to make their first meaningful contribution?', 'anchored5', '[{"value":1,"label":">12 weeks","description":null},{"value":2,"label":"8-12 weeks","description":null},{"value":3,"label":"4-8 weeks","description":null},{"value":4,"label":"2-4 weeks","description":null},{"value":5,"label":"<2 weeks","description":null}]'::jsonb, false, true, false),
  ('C5L-02', 'M-C5-TL', 2, 'How structured is your team''s onboarding for new members?', 'anchored5', '[{"value":1,"label":"No structure","description":null},{"value":5,"label":"Highly structured with clear milestones","description":null}]'::jsonb, false, true, false),
  ('C5L-03', 'M-C5-TL', 3, 'When a new tool or process is introduced, how long until your team is using it productively?', 'anchored5', '[{"value":1,"label":">90 days","description":null},{"value":5,"label":"<30 days","description":null}]'::jsonb, false, true, false),
  ('C5L-04', 'M-C5-TL', 4, 'How smoothly does your team adopt new tools or processes?', 'anchored5', '[{"value":1,"label":"Significant resistance/disruption","description":null},{"value":5,"label":"Smooth and rapid","description":null}]'::jsonb, false, true, false),
  ('C5L-05', 'M-C5-TL', 5, 'How often does your team formally review what worked and what didn''t on completed work?', 'anchored5', '[{"value":1,"label":"Never","description":null},{"value":2,"label":"Rarely","description":null},{"value":3,"label":"Sometimes","description":null},{"value":4,"label":"Regularly","description":null},{"value":5,"label":"After every significant piece of work","description":null}]'::jsonb, false, true, false),
  ('C5L-06', 'M-C5-TL', 6, 'When your team identifies a learning from a retrospective, how reliably does it get applied to subsequent work?', 'anchored5', '[{"value":1,"label":"Rarely","description":null},{"value":5,"label":"Almost always","description":null}]'::jsonb, false, true, false),
  ('C5L-07', 'M-C5-TL', 7, 'How regularly does your team share learning or new knowledge across team members?', 'anchored5', '[{"value":1,"label":"Rarely","description":null},{"value":5,"label":"As a regular practice","description":null}]'::jsonb, false, true, false),
  ('C5L-08', 'M-C5-TL', 8, 'When a team member learns something new and useful, how easily does the rest of the team gain access to that knowledge?', 'anchored5', '[{"value":1,"label":"Difficult","description":null},{"value":5,"label":"Effortless","description":null}]'::jsonb, false, true, false),
  ('C5L-09', 'M-C5-TL', 9, 'How safe is it for your team members to try new approaches that might not work?', 'anchored5', '[{"value":1,"label":"Not safe — failures are penalised","description":null},{"value":5,"label":"Very safe — experimentation is encouraged","description":null}]'::jsonb, false, true, false),
  ('C5L-10', 'M-C5-TL', 10, 'How does your team treat mistakes and failures?', 'anchored5', '[{"value":1,"label":"Punitive","description":null},{"value":5,"label":"As learning opportunities","description":null}]'::jsonb, false, true, false),
  ('C5L-11', 'M-C5-TL', 11, 'How readily does your team accept the temporary or permanent transfer of team members to or from other teams?', 'anchored5', '[{"value":1,"label":"Significant friction","description":null},{"value":5,"label":"Smooth and embraced","description":null}]'::jsonb, false, true, false),
  ('C5L-12', 'M-C5-TL', 12, 'How actively does your team consume external learning (industry conferences, courses, professional reading)?', 'anchored5', '[{"value":1,"label":"Minimally","description":null},{"value":5,"label":"Highly actively","description":null}]'::jsonb, false, true, false)
on conflict (code) do update set
  module_code = excluded.module_code,
  position = excluded.position,
  wording = excluded.wording,
  response_kind = excluded.response_kind,
  anchors = excluded.anchors,
  is_reverse = excluded.is_reverse,
  online = excluded.online,
  portal_code = excluded.portal_code;

-- ref_admin_checklists: 3 rows.
insert into public.ref_admin_checklists (code, repeats_over, minimum_facts, source, position) values
  ('ADM-O1', 'role_family', null, 'Online Measurement Specification 4.2', 1),
  ('ADM-O2', 'system', null, 'Online Measurement Specification 4.3', 2),
  ('ADM-O4', 'unit', 3, 'Online Measurement Specification 4.3a', 3)
on conflict (code) do update set
  repeats_over = excluded.repeats_over,
  minimum_facts = excluded.minimum_facts,
  source = excluded.source,
  position = excluded.position;

-- ref_admin_checklist_facts: 12 rows.
insert into public.ref_admin_checklist_facts (code, checklist_code, position, wording, response_kind, source_response) values
  ('RA-1', 'ADM-O1', 1, 'A written position description exists and was reviewed or updated within the last 24 months.', 'yes_no', null),
  ('RA-2', 'ADM-O1', 2, 'The position description states success measures or accountabilities, not only duties.', 'yes_no', null),
  ('RA-3', 'ADM-O1', 3, 'The position description, or a delegations document it refers to, states the decisions the role can make without approval.', 'yes_no', null),
  ('TI-1', 'ADM-O2', 1, 'The system has a named owner accountable for it.', 'yes_no', 'Yes 1, No 0'),
  ('TI-2', 'ADM-O2', 2, 'The system is on a current, vendor-supported version.', 'yes_no', 'Yes 1, No 0'),
  ('TI-3', 'ADM-O2', 3, 'The system does the job the unit needs without routine offline workarounds such as spreadsheets or re-keying.', 'yes_partly_no', 'Yes 1, Partly 0.5, No 0'),
  ('INT-1', 'ADM-O2', 4, 'How data moves between this system and the others the unit relies on.', 'integration', 'Automated integration 100; scheduled import or export 60; manual re-entry 20; not connected but should be 0; does not need to connect (excluded)'),
  ('CF-1', 'ADM-O4', 1, 'Workload to capacity (utilisation), %', 'percent', '80 to 95 = 100; 95 to 105 or 70 to 80 = 75; 105 to 115 or 60 to 70 = 55; above 115 or below 60 = 25'),
  ('CF-2', 'ADM-O4', 2, 'Hours worked per FTE per week above standard', 'hours', 'up to 1 = 100; 1 to 2 = 85; 2 to 4 = 65; 4 to 6 = 45; above 6 = 20'),
  ('CF-3', 'ADM-O4', 3, 'Unplanned absence against the organisation''s own 12-month baseline', 'percent', 'at or below = 100; up to 10% above = 75; 10 to 25% above = 55; more than 25% above = 25'),
  ('CF-4', 'ADM-O4', 4, 'Change in open backlog over the last three months', 'percent_or_na', 'shrinking or stable (within 5%) = 100; growing 5 to 25% = 55; growing more than 25% = 25; not applicable (excluded)'),
  ('CF-5', 'ADM-O4', 5, 'Vacancy rate against approved establishment', 'percent', 'up to 3% = 100; 3 to 6 = 85; 6 to 10 = 65; 10 to 15 = 45; above 15 = 20')
on conflict (code) do update set
  checklist_code = excluded.checklist_code,
  position = excluded.position,
  wording = excluded.wording,
  response_kind = excluded.response_kind,
  source_response = excluded.source_response;

-- ref_admin_checklist_values: 19 rows.
insert into public.ref_admin_checklist_values (fact_code, option, label, value, position) values
  ('RA-1', 'yes', 'Yes', 1, 1),
  ('RA-1', 'no', 'No', 0, 2),
  ('RA-2', 'yes', 'Yes', 1, 1),
  ('RA-2', 'no', 'No', 0, 2),
  ('RA-3', 'yes', 'Yes', 1, 1),
  ('RA-3', 'no', 'No', 0, 2),
  ('TI-1', 'yes', 'Yes', 1, 1),
  ('TI-1', 'no', 'No', 0, 2),
  ('TI-2', 'yes', 'Yes', 1, 1),
  ('TI-2', 'no', 'No', 0, 2),
  ('TI-3', 'yes', 'Yes', 1, 1),
  ('TI-3', 'partly', 'Partly', 0.5, 2),
  ('TI-3', 'no', 'No', 0, 3),
  ('INT-1', 'automated', 'Automated integration', 100, 1),
  ('INT-1', 'scheduled', 'scheduled import or export', 60, 2),
  ('INT-1', 'manual', 'manual re-entry', 20, 3),
  ('INT-1', 'not-connected', 'not connected but should be', 0, 4),
  ('INT-1', 'excluded', 'does not need to connect', null, 5),
  ('CF-4', 'not-applicable', 'not applicable', null, 1)
on conflict (fact_code, option) do update set
  label = excluded.label,
  value = excluded.value,
  position = excluded.position;

-- ref_admin_checklist_bands: 24 rows.
insert into public.ref_admin_checklist_bands (fact_code, position, score, lower, lower_inclusive, upper, upper_inclusive) values
  ('CF-1', 1, 100, 80, true, 95, true),
  ('CF-1', 2, 75, 70, true, 80, false),
  ('CF-1', 3, 75, 95, false, 105, true),
  ('CF-1', 4, 55, 60, true, 70, false),
  ('CF-1', 5, 55, 105, false, 115, true),
  ('CF-1', 6, 25, null, false, 60, false),
  ('CF-1', 7, 25, 115, false, null, false),
  ('CF-2', 1, 100, null, false, 1, true),
  ('CF-2', 2, 85, 1, false, 2, true),
  ('CF-2', 3, 65, 2, false, 4, true),
  ('CF-2', 4, 45, 4, false, 6, true),
  ('CF-2', 5, 20, 6, false, null, false),
  ('CF-3', 1, 100, null, false, 0, true),
  ('CF-3', 2, 75, 0, false, 10, true),
  ('CF-3', 3, 55, 10, false, 25, true),
  ('CF-3', 4, 25, 25, false, null, false),
  ('CF-4', 1, 100, null, false, 5, true),
  ('CF-4', 2, 55, 5, false, 25, true),
  ('CF-4', 3, 25, 25, false, null, false),
  ('CF-5', 1, 100, null, false, 3, true),
  ('CF-5', 2, 85, 3, false, 6, true),
  ('CF-5', 3, 65, 6, false, 10, true),
  ('CF-5', 4, 45, 10, false, 15, true),
  ('CF-5', 5, 20, 15, false, null, false)
on conflict (fact_code, position) do update set
  score = excluded.score,
  lower = excluded.lower,
  lower_inclusive = excluded.lower_inclusive,
  upper = excluded.upper,
  upper_inclusive = excluded.upper_inclusive;

-- ref_event_triggers: 16 rows.
insert into public.ref_event_triggers (code, source_trigger, affects, detection, deploys, source, position) values
  ('headcount_change', 'Unit headcount change >20% in a quarter', array['C1', 'C4', 'S1'], 'directory', 'affected', 'Cadence Master 7.3', 1),
  ('new_manager', 'New manager into the unit', array['O5', 'S3'], 'directory', 'affected', 'Cadence Master 7.3', 2),
  ('manager_development', 'Manager-development programme completion', array['O5', 'M1', 'M2'], 'menu', 'affected', 'Cadence Master 7.3', 3),
  ('reorganisation', 'Major reorganisation affecting decision rights', array['O1'], 'menu', 'affected', 'Cadence Master 7.3', 4),
  ('tool_rollout', 'Major tool rollout (ERP, CRM, AI)', array['O2'], 'menu', 'affected', 'Cadence Master 7.3', 5),
  ('process_redesign', 'Major process redesign', array['O3'], 'menu', 'affected', 'Cadence Master 7.3', 6),
  ('strategy_change', 'New enterprise strategy or pivot', array['O1', 'M4'], 'menu', 'affected', 'Cadence Master 7.3', 7),
  ('grievance', 'Reported speak-up or grievance incident', array['M2', 'S3', 'TW1', 'TW2', 'TW3'], 'menu', 'affected', 'Cadence Master 7.3', 8),
  ('pulse_drop', 'Two or more pulse indicators drop >10 points', '{}'::text[], 'menu', 'half_yearly', 'Cadence Master 7.3', 9),
  ('pay_equity_audit', 'Pay equity audit pending or recent', array['TW1'], 'menu', 'affected', 'Cadence Master 7.3', 10),
  ('whs_incident', 'WHS incident in the unit', array['TW3', 'M2'], 'menu', 'affected', 'Cadence Master 7.3', 11),
  ('backlog_growth', 'Backlog growth >25% or burnout indicators', array['O4'], 'menu', 'affected', 'Cadence Master 7.3', 12),
  ('meeting_overload', 'Sustained meeting overload signal in Workplace Analytics', array['S2'], 'menu', 'affected', 'Cadence Master 7.3', 13),
  ('turnover_spike', 'Voluntary turnover spike in a specific manager''s team', array['O5'], 'menu', 'affected', 'Cadence Master 7.3', 14),
  ('complaint_spike', 'Customer complaint spike on a process-related issue', array['O3'], 'menu', 'affected', 'Cadence Master 7.3', 15),
  ('team_composition_change', 'Team composition change above 30%', array['C4'], 'directory', 'affected', 'Online Measurement Specification 6.3', 16)
on conflict (code) do update set
  source_trigger = excluded.source_trigger,
  affects = excluded.affects,
  detection = excluded.detection,
  deploys = excluded.deploys,
  source = excluded.source,
  position = excluded.position;

delete from public.ref_event_triggers where code not in ('headcount_change', 'new_manager', 'manager_development', 'reorganisation', 'tool_rollout', 'process_redesign', 'strategy_change', 'grievance', 'pulse_drop', 'pay_equity_audit', 'whs_incident', 'backlog_growth', 'meeting_overload', 'turnover_spike', 'complaint_spike', 'team_composition_change');
delete from public.ref_admin_checklist_bands where (fact_code, position) not in (('CF-1', 1), ('CF-1', 2), ('CF-1', 3), ('CF-1', 4), ('CF-1', 5), ('CF-1', 6), ('CF-1', 7), ('CF-2', 1), ('CF-2', 2), ('CF-2', 3), ('CF-2', 4), ('CF-2', 5), ('CF-3', 1), ('CF-3', 2), ('CF-3', 3), ('CF-3', 4), ('CF-4', 1), ('CF-4', 2), ('CF-4', 3), ('CF-5', 1), ('CF-5', 2), ('CF-5', 3), ('CF-5', 4), ('CF-5', 5));
delete from public.ref_admin_checklist_values where (fact_code, option) not in (('RA-1', 'yes'), ('RA-1', 'no'), ('RA-2', 'yes'), ('RA-2', 'no'), ('RA-3', 'yes'), ('RA-3', 'no'), ('TI-1', 'yes'), ('TI-1', 'no'), ('TI-2', 'yes'), ('TI-2', 'no'), ('TI-3', 'yes'), ('TI-3', 'partly'), ('TI-3', 'no'), ('INT-1', 'automated'), ('INT-1', 'scheduled'), ('INT-1', 'manual'), ('INT-1', 'not-connected'), ('INT-1', 'excluded'), ('CF-4', 'not-applicable'));
delete from public.ref_admin_checklist_facts where code not in ('RA-1', 'RA-2', 'RA-3', 'TI-1', 'TI-2', 'TI-3', 'INT-1', 'CF-1', 'CF-2', 'CF-3', 'CF-4', 'CF-5');
delete from public.ref_admin_checklists where code not in ('ADM-O1', 'ADM-O2', 'ADM-O4');
delete from public.ref_module_items where code not in ('O1C-01', 'O1C-02', 'O1C-03', 'O1C-04', 'O1C-05', 'O2I-01', 'O2I-02', 'O2I-03', 'O2I-04', 'O2I-05', 'O2I-06', 'O2I-07', 'O3P-01', 'O3P-02', 'O3P-03', 'O3P-04', 'O3P-05', 'O3P-06', 'O3P-07', 'O1L-01', 'O1L-02', 'O1L-03', 'O1L-04', 'O1L-05', 'O1L-06', 'C1M-01', 'C2M-01', 'C3M-01', 'C3M-02', 'C5L-01', 'C5L-02', 'C5L-03', 'C5L-04', 'C5L-05', 'C5L-06', 'C5L-07', 'C5L-08', 'C5L-09', 'C5L-10', 'C5L-11', 'C5L-12');
delete from public.ref_modules where code not in ('M-O1-CASCADE', 'M-O2-IA', 'M-O3-PF', 'M-O1-LT', 'M-C1-MGR', 'M-C2-MGR', 'M-C3-MGR', 'M-C5-TL');
delete from public.ref_pulse_rotation where (rotation, item_code) not in ((1, 'TSI2-01'), (1, 'TSI2-02'), (1, 'CII-13'), (1, 'TSI2-03'), (1, 'OI5-01'), (1, 'OI5-02'), (1, 'OI5-03'), (1, 'MI1-01'), (1, 'MI1-02'), (1, 'MI1-05'), (1, 'MI1-07'), (1, 'MI1-04'), (1, 'MI2-01'), (1, 'MI2-02'), (1, 'MI2-03'), (1, 'TW-01'), (1, 'TW-02'), (2, 'TSI2-01'), (2, 'TSI2-02'), (2, 'CII-13'), (2, 'TSI2-03'), (2, 'OI5-01'), (2, 'OI5-02'), (2, 'OI5-03'), (2, 'MI1-01'), (2, 'MI1-03'), (2, 'MI1-05'), (2, 'MI1-08'), (2, 'MI1-04'), (2, 'MI2-01'), (2, 'MI2-02'), (2, 'MI2-04'), (2, 'TW-02'), (2, 'TW-03'), (3, 'TSI2-01'), (3, 'TSI2-02'), (3, 'CII-13'), (3, 'TSI2-03'), (3, 'OI5-01'), (3, 'OI5-02'), (3, 'OI5-03'), (3, 'MI1-02'), (3, 'MI1-03'), (3, 'MI1-05'), (3, 'MI1-06'), (3, 'MI1-07'), (3, 'MI2-02'), (3, 'MI2-03'), (3, 'MI2-05'), (3, 'TW-01'), (3, 'TW-03'), (4, 'TSI2-01'), (4, 'TSI2-02'), (4, 'CII-13'), (4, 'TSI2-03'), (4, 'OI5-01'), (4, 'OI5-02'), (4, 'OI5-03'), (4, 'MI1-01'), (4, 'MI1-02'), (4, 'MI1-06'), (4, 'MI1-08'), (4, 'MI1-04'), (4, 'MI2-01'), (4, 'MI2-03'), (4, 'MI2-04'), (4, 'TW-01'), (4, 'TW-02'));
delete from public.ref_survey_items where code not in ('CII-01', 'CII-02', 'CII-06', 'CII-07', 'CII-11', 'CII-12', 'TSI2-01', 'TSI2-02', 'TSI3-01', 'TSI3-02', 'CII-03', 'CII-04', 'CII-08', 'CII-09', 'CII-13', 'CII-14', 'TSI2-03', 'TSI3-03', 'TSI3-04', 'TSI3-05', 'CII-05', 'CII-10', 'CII-15', 'OI1-01', 'OI1-02', 'OI1-04', 'OI1-05', 'OI1-07', 'OI1-08', 'OI1-03', 'OI1-06', 'OI2-01', 'OI2-02', 'OI2-03', 'OI2-04', 'OI3-01', 'OI3-02', 'OI3-03', 'OI3-04', 'OI3-05', 'OI4-01', 'OI4-02', 'OI4-03', 'OI5-01', 'OI5-02', 'OI5-03', 'MI1-01', 'MI1-02', 'MI1-03', 'MI1-05', 'MI1-06', 'MI1-07', 'MI1-08', 'MI1-04', 'MI2-01', 'MI2-02', 'MI2-03', 'MI2-04', 'MI2-05', 'MI3-01', 'MI3-02', 'MI3-03', 'MI3-05', 'MI3-04', 'MI4-01', 'MI4-02', 'MI4-03', 'MI4-04', 'TW-01', 'TW-02', 'TW-03');
delete from public.ref_survey_sections where code not in ('A', 'B', 'C');
