"use client";

import { useActionState } from "react";

import { Field, Notice, SubmitButton } from "@/components/ui";
import type { EnrolFormState } from "@/lib/auth/form-state";
import { authCopy } from "@/lib/copy/auth";

import { enrolTotp } from "../actions";

export function EnrolForm() {
  const [state, action, pending] = useActionState<EnrolFormState, FormData>(enrolTotp, {
    step: "start",
  });

  if (state.step === "start") {
    return (
      <form action={action}>
        {state.error ? <Notice tone="problem">{state.error}</Notice> : null}
        <input type="hidden" name="intent" value="start" />
        <SubmitButton pending={pending}>{authCopy["mfa.enrol.start"]}</SubmitButton>
      </form>
    );
  }

  return (
    <form action={action}>
      {state.error ? <Notice tone="problem">{state.error}</Notice> : null}
      <p className="text-sm text-grey">{authCopy["mfa.enrol.scan"]}</p>
      {state.qrCode ? (
        // The QR code is an SVG data URL generated by Supabase; next/image adds nothing here.
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={state.qrCode}
          alt={authCopy["mfa.enrol.qrAlt"]}
          width={180}
          height={180}
          className="mt-3 border border-grey-20 bg-white p-2"
        />
      ) : null}
      <p className="mt-4 text-sm text-grey">{authCopy["mfa.enrol.secret"]}</p>
      <p className="mt-1 break-all font-mono text-sm text-slate" data-testid="totp-secret">
        {state.secret}
      </p>
      <input type="hidden" name="intent" value="verify" />
      <input type="hidden" name="factorId" value={state.factorId ?? ""} />
      <div className="mt-6">
        <Field
          label={authCopy["mfa.enrol.code"]}
          name="code"
          inputMode="numeric"
          autoComplete="one-time-code"
        />
      </div>
      <SubmitButton pending={pending}>{authCopy["mfa.enrol.submit"]}</SubmitButton>
    </form>
  );
}
